language: c

sudo: required

services:
  - docker

compiler:
  - clang
  - gcc

env:
  - BOOST_TEST_LOG_LEVEL=all

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install libboost-all-dev
  - sudo apt-get install libssl-dev libjansson-dev libxml2-dev
  - sudo apt-get install libmozjs185-dev python-dev lua5.2 liblua5.2-dev
  - sudo apt-get install libedit-dev

install:
  - git clone https://github.com/cybergarage/mupnpc.git mupnp
  - pushd mupnp && ./bootstrap && ./configure_linux && make && sudo make install && popd

script:
  - ./bootstrap && ./configure_linux --enable-tests && make && make check

notifications:
  email: false

after_success:
  - docker login -e $CG_DOCKER_EMAIL -u $CG_DOCKER_USER -p $CG_DOCKER_PASS
  - pushd pkg/docker/round-dev && sudo docker build -t cybergarage/round-dev:latest . && popd
  - sudo docker push cybergarage/round-dev:latest
  - pushd pkg/docker/round && sudo docker build -t cybergarage/round:latest --no-cache . && popd
  - sudo docker push cybergarage/round:latest
