#!/bin/sh

cd include/round && ./const.h.build && cd ../..
cd src/round/impl && ./upnp_server_desc.h.build && cd ../../../
# ./format

cd include && ./Makefile.am.build > Makefile.am && cd ..
cd lib/unix && ./Makefile.am.build > Makefile.am && cd ../..
cd bin/round/unix && ./Makefile.am.build > Makefile.am && cd ../../..
cd bin/roundd/unix && ./Makefile.am.build > Makefile.am && cd ../../..
cd tests/unix && ./Makefile.am.build > Makefile.am && cd ../..

if [ ! -d config ]; then
    mkdir config
fi
if [ ! -d autom4te.cache ]; then
	rm -rf autom4te.cache/*
fi
#libtoolize --automake --force --copy
aclocal
autoheader
automake --foreign --add-missing --copy
autoconf 
