/******************************************************************
 *
 * Round for C
 *
 * Copyright (C) Satoshi Konno 2015
 *
 * This is licensed under BSD-style license, see file COPYING.
 *
 ******************************************************************/

#ifndef _ROUNDC_CONST_H_
#define _ROUNDC_CONST_H_

#ifdef  __cplusplus
extern "C" {
#endif

#define ROUND_PRODUCT_NAME "round"
#define ROUND_MODULE_NAME "round"
#define ROUND_SYSTEM_TRIGGER_TIMER_PRECISION 0.1
#define ROUND_ENDL "\n"
#define ROUND_MD5_DIGEST_LENGTH 16
#define ROUND_MD5_DIGEST_STRING_LENGTH 32
#define ROUND_SHA_DIGEST_LENGTH 20
#define ROUND_SHA_DIGEST_STRING_LENGTH 40
#define ROUND_SHA256_DIGEST_LENGTH 32
#define ROUND_SHA256_DIGEST_STRING_LENGTH 64
#define ROUND_NODE_DIGEST_LENGTH 64
#define ROUND_UPNP_DEVICE_TYPE "urn:cybergarage-org:device:round:1"
#define ROUND_UPNP_SERVICE_TYPE "urn:cybergarage-org:service:round:1"
#define ROUND_UPNP_ACTION_GETPRODUCTINFO "GetProductInfo"
#define ROUND_UPNP_ACTION_GETCONNECTIONINFO "GetConnectionInfo"
#define ROUND_RPC_HTTP_ENDPOINT "/rpc"
#define ROUND_RPC_HTTP_CONTENT_TYPE "application/json-rpc"
#define ROUND_RPC_HTTP_STATUS_CODE_OK 200 
#define ROUND_RPC_HTTP_STATUS_CODE_MOVED_PERMANENTLY 301 
#define ROUND_RPC_HTTP_STATUS_CODE_BAD_REQUEST 400 
#define ROUND_RPC_HTTP_STATUS_CODE_NOT_FOUND 404 
#define ROUND_RPC_HTTP_STATUS_CODE_NOT_ACCEPTABLE 406 
#define ROUND_RPC_HTTP_STATUS_CODE_INTERNAL_SERVER_ERROR 500
#define ROUND_NODE_STATUS_UNKNOWN 0
#define ROUND_NODE_STATUS_STOP 1
#define ROUND_NODE_STATUS_ACTIVATING 2
#define ROUND_NODE_STATUS_ACTIVE 3
#define ROUND_NODE_STATUS_TERMINATING 4
#define ROUND_NODE_STATUS_PROMICE 5
#define ROUND_ENCODING_NONE 0
#define ROUND_ENCODING_BASE64 1
#define ROUND_JSON_RPC_JSONRPC "jsonrpc"
#define ROUND_JSON_RPC_METHOD "method"
#define ROUND_JSON_RPC_PARAMS "params"
#define ROUND_JSON_RPC_ID "id"
#define ROUND_JSON_RPC_DEST "dest"
#define ROUND_JSON_RPC_TS "ts"
#define ROUND_JSON_RPC_RESULT "result"
#define ROUND_JSON_RPC_ERROR "error"
#define ROUND_JSON_RPC_CODE "code"
#define ROUND_JSON_RPC_MESSAGE "message"
#define ROUND_JSON_RPC_VERSION "2.0"
#define ROUND_JSON_RPC_REQUEST_TIMEOUT_SEC 60
#define ROUND_MODULE_PARAM_NAME "name"
#define ROUND_MODULE_PARAM_VERSION "version"
#define ROUND_MODULE_PARAM_METHODS "methods"
#define ROUND_MODULE_PARAM_ENCODE "enc"
#define ROUND_MODULE_PARAM_LANGUAGE "lang"
#define ROUND_MODULE_PARAM_CODE "code"
#define ROUND_MODULE_PARAM_URL "url"
#define ROUND_SYSTEM_METHOD_POST_JOB "post_job"
#define ROUND_SYSTEM_METHOD_POST_METHOD "post_method"
#define ROUND_SYSTEM_METHOD_SET_METHOD "set_method"
#define ROUND_SYSTEM_METHOD_SET_ALIAS "set_alias"
#define ROUND_SYSTEM_METHOD_SET_ROUTE "set_route"
#define ROUND_SYSTEM_METHOD_SET_TIMER "set_timer"
#define ROUND_SYSTEM_METHOD_ADD_NODE "add_node"
#define ROUND_SYSTEM_METHOD_REMOVE_METHOD "remove_method"
#define ROUND_SYSTEM_METHOD_REMOVE_ALIAS "remove_alias"
#define ROUND_SYSTEM_METHOD_REMOVE_ROUTE "remove_route"
#define ROUND_SYSTEM_METHOD_REMOVE_TIMER "remove_timer"
#define ROUND_SYSTEM_METHOD_REMOVE_NODE "remove_node"
#define ROUND_SYSTEM_METHOD_ECHO "_echo"
#define ROUND_SYSTEM_METHOD_GET_NETWORK_STATE "get_network_state"
#define ROUND_SYSTEM_METHOD_GET_CLUSTER_STATE "get_cluster_state"
#define ROUND_SYSTEM_METHOD_SET_REGISTRY "set_registry"
#define ROUND_SYSTEM_METHOD_GET_REGISTRY "get_registry"
#define ROUND_SYSTEM_METHOD_REMOVE_REGISTRY "remove_registry"
#define ROUND_SYSTEM_METHOD_GET_NODE_STATE "get_node_state"
#define ROUND_SYSTEM_METHOD_GET_NODE_CONFIG "get_node_config"
#define ROUND_SYSTEM_METHOD_PARAM_ID "id"
#define ROUND_SYSTEM_METHOD_PARAM_NAME "name"
#define ROUND_SYSTEM_METHOD_PARAM_LANGUAGE "lang"
#define ROUND_SYSTEM_METHOD_PARAM_CODE "code"
#define ROUND_SYSTEM_METHOD_PARAM_ENCODE "enc"
#define ROUND_SYSTEM_METHOD_PARAM_BASE64 "base64"
#define ROUND_SYSTEM_METHOD_PARAM_KEY "key"
#define ROUND_SYSTEM_METHOD_PARAM_VALUE "val"
#define ROUND_SYSTEM_METHOD_PARAM_TS "ts"
#define ROUND_SYSTEM_METHOD_PARAM_LTS "lts"
#define ROUND_SYSTEM_METHOD_PARAM_SRC "src"
#define ROUND_SYSTEM_METHOD_PARAM_DEST "dest"
#define ROUND_SYSTEM_METHOD_PARAM_TYPE "type"
#define ROUND_SYSTEM_METHOD_PARAM_COND "cond"
#define ROUND_SYSTEM_METHOD_PARAM_ADDR "addr"
#define ROUND_SYSTEM_METHOD_PARAM_PORT "port"
#define ROUND_SYSTEM_METHOD_PARAM_HASH "hash"
#define ROUND_SYSTEM_METHOD_PARAM_VERSION "version"
#define ROUND_SYSTEM_METHOD_PARAM_NODES "nodes"
#define ROUND_SYSTEM_METHOD_PARAM_CLUSTER "cluster"
#define ROUND_SYSTEM_METHOD_PARAM_CLUSTERS "clusters"
#define ROUND_SYSTEM_METHOD_PARAM_STATE "state"
#define ROUND_SYSTEM_METHOD_PARAM_METHOD "method"
#define ROUND_SYSTEM_METHOD_PARAM_DEFAULTS "defaults"
#define ROUND_SYSTEM_METHOD_PARAM_START_TIME "start_time"
#define ROUND_SYSTEM_METHOD_PARAM_STOP_TIME "stop_time"
#define ROUND_SYSTEM_METHOD_PARAM_DURATION "duration"
#define ROUND_SYSTEM_METHOD_PARAM_LOOP "loop"
#define ROUND_SYSTEM_METHOD_ADD_NODE_CMD "/usr/local/bin/roundd"
#define ROUND_SYSTEM_METHOD_REMOVE_NODE_DELAY_MSEC 5000
#define ROUND_SYSTEM_METHOD_DEST_ALL_NODE "*"
#define ROUND_SYSTEM_METHOD_DEST_ANY_NODE "?"
#define ROUND_SYSTEM_METHOD_DEST_LOCAL_NODE "."
#define ROUND_SCRIPT_LANGUAGE_JS "js"
#define ROUND_SCRIPT_LANGUAGE_RUBY "ruby"
#define ROUND_SCRIPT_LANGUAGE_LUA "lua"
#define ROUND_SCRIPT_LANGUAGE_PYTHON "python"
#define ROUND_SCRIPT_LANGUAGE_JAVA "java"
#define ROUND_SCRIPT_POST_METHOD "post_method"
#define ROUND_SCRIPT_PRINT_METHOD "print"
#define ROUND_SCRIPT_SEARCH_METHOD "search"
#define ROUND_SCRIPT_SEARCH_METHOD_WAIT_MSEC 5000

#define ROUND_DEFAULT_NODE_CLUSTER_NAME "round"
#define ROUND_DEFAULT_NODE_BIND_PORT 38400

#define ROUND_MSG_SEARCHING "Searching"
#define ROUND_MSG_DONE "Done"

#define ROUND_RPC_ERROR_CODE_UNKNOWN 0
#define ROUND_RPC_ERROR_CODE_PARSER_ERROR -32700
#define ROUND_RPC_ERROR_CODE_INVALID_REQUEST -32600
#define ROUND_RPC_ERROR_CODE_METHOD_NOT_FOUND -32601
#define ROUND_RPC_ERROR_CODE_INVALID_PARAMS -32602
#define ROUND_RPC_ERROR_CODE_INTERNAL_ERROR -32603
#define ROUND_RPC_ERROR_CODE_BAD_DESTINATION -32000
#define ROUND_RPC_ERROR_CODE_MOVED_PERMANENTLY -32001
#define ROUND_RPC_ERROR_CODE_CONDITION_FAILED -32010
#define ROUND_RPC_ERROR_CODE_SCRIPT_ENGINE_INTERNAL_ERROR -32020
#define ROUND_RPC_ERROR_CODE_SCRIPT_ENGINE_NOT_FOUND -32021
#define ROUND_RPC_ERROR_CODE_SCRIPT_COMPILE_ERROR -32022
#define ROUND_RPC_ERROR_CODE_SCRIPT_RUNTIME_ERROR -32023
#define ROUND_RPC_ERROR_CODE_SERVER_ERROR_MAX -32000
#define ROUND_RPC_ERROR_CODE_SERVER_ERROR_MIN -32099

#define ROUND_RPC_ERROR_CODE_UNKNOWN_MSG  "Unknown Error"
#define ROUND_RPC_ERROR_CODE_PARSER_ERROR_MSG  "Parse error"
#define ROUND_RPC_ERROR_CODE_INVALID_REQUEST_MSG  "Invalid Request"
#define ROUND_RPC_ERROR_CODE_METHOD_NOT_FOUND_MSG  "Method not found"
#define ROUND_RPC_ERROR_CODE_INVALID_PARAMS_MSG  "Invalid params"
#define ROUND_RPC_ERROR_CODE_INTERNAL_ERROR_MSG  "Internal error"
#define ROUND_RPC_ERROR_CODE_BAD_DESTINATION_MSG  "Bad Destination"
#define ROUND_RPC_ERROR_CODE_MOVED_PERMANENTLY_MSG  "Moved Permanently"
#define ROUND_RPC_ERROR_CODE_CONDITION_FAILED_MSG  "Condition Failed"
#define ROUND_RPC_ERROR_CODE_SCRIPT_ENGINE_INTERNAL_ERROR_MSG  "Script Engine Internal Error"
#define ROUND_RPC_ERROR_CODE_SCRIPT_ENGINE_NOT_FOUND_MSG  "Script Engine Not Found"
#define ROUND_RPC_ERROR_CODE_SCRIPT_COMPILE_ERROR_MSG  "Script Compile Error"
#define ROUND_RPC_ERROR_CODE_SCRIPT_RUNTIME_ERROR_MSG  "Script Runtime Error"

#ifdef  __cplusplus
} /* extern C */
#endif

#endif
